# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loginn_1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 800)
        Form.setMinimumSize(QtCore.QSize(800, 800))
        Form.setMaximumSize(QtCore.QSize(800, 800))
        Form.setStyleSheet("Coinport")
        Form.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        Form.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        self.bg1 = QtWidgets.QLabel(Form)
        self.bg1.setGeometry(QtCore.QRect(190, 110, 381, 461))
        self.bg1.setStyleSheet("background-color: rgb(0, 0, 0);border-radius:30px")
        self.bg1.setText("")
        self.bg1.setObjectName("bg1")
        self.bg2 = QtWidgets.QLabel(Form)
        self.bg2.setGeometry(QtCore.QRect(215, 130, 331, 421))
        self.bg2.setStyleSheet("background-color: rgb(39, 39, 39);;border-radius:30px\n"
"\n"
"\n"
"")
        self.bg2.setText("")
        self.bg2.setObjectName("bg2")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(270, 140, 231, 71))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(262, 240, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background-color: rgb(3, 103, 139);border-radius:20px;border:none;color:white;padding-left:10px;\n"
"")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(262, 330, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(12)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("background-color: rgb(3, 103, 139);border-radius:20px;border:none;color:white;padding-left:10px;\n"
"")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(320, 420, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{color: rgb(255, 255, 255);background-color: rgb(3, 103, 139);border:none;border-radius:20px;transition-duration0.5s;}\n"
"QPushButton::hover{color:black;}\n"
"")
        self.pushButton.setAutoDefault(True)
        self.pushButton.setDefault(False)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(320, 480, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton{color: rgb(255, 255, 255);background-color: rgb(3, 103, 139);border:none;border-radius:20px;transition-duration0.5s;}\n"
"QPushButton::hover{color:black;}\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Coinport"))
        self.label.setText(_translate("Form", "Coinport"))
        self.lineEdit.setPlaceholderText(_translate("Form", "Kullanıcı Adı"))
        self.lineEdit_2.setPlaceholderText(_translate("Form", "Şifre"))
        self.pushButton.setText(_translate("Form", "Giriş Yap"))
        self.pushButton_2.setText(_translate("Form", "Kayıt Ol"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
